var data = {
  "admin" : "Veer",
  "events" : {
    "AI Why the hype now" : {
      "btnValue" : "Register",
      "date" : "02-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/elqjbpd58vj5b6l/AIS.png?raw=1",
      "name" : "AI-Why the hype now?",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/techtalkInspiro",
      "time" : "10:00 AM",
      "timeStamp" : 1551465000,
      "venue" : "MV Hall, GJB"
    },
    "AR applications" : {
      "btnValue" : "Register",
      "date" : "26-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/0q52yicfxju4g8t/AR.jpeg?raw=1",
      "name" : "AR Applications",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/nisbarreg",
      "time" : "10:00 AM",
      "timeStamp" : 1569456000,
      "venue" : "Azeez Sait Hall"
    },
    "AT&S Visit" : {
      "btnValue" : "Register",
      "date" : "16-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/jny61t8uxvl710v/93a7faa7-5aed-498a-b3db-dfd93f8dbec2.png?raw=1",
      "name" : "AT&S Visit",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/ankuraIV",
      "time" : "2:00 PM",
      "timeStamp" : 1552674600,
      "venue" : "Golden Jubliee Block"
    },
    "Adroit'18" : {
      "btnValue" : "Open For All",
      "date" : "04-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/vmwp0203iiyu6gc/Adroit%2718_Updated.png?raw=1",
      "name" : "Adroit'18",
      "organiser" : "NISB",
      "regUrl" : "",
      "time" : "9:30 AM",
      "timeStamp" : 1538591400,
      "venue" : "MV Hall, GJB"
    },
    "Alexa Workshop" : {
      "btnValue" : "Register",
      "date" : "29-09-2018",
      "imgUrl" : "https://www.dropbox.com/s/5dqmhfvl0zuvo7c/alexafinalnew%281%29%20%281%29.png?raw=1",
      "name" : "Alexa Workshop",
      "organiser" : "NISB",
      "regUrl" : "http://www.bit.ly/alexaNISB",
      "time" : "10:00 AM",
      "timeStamp" : 1538159400,
      "venue" : "Browsing Center"
    },
    "Amazon Web Services" : {
      "btnValue" : "Registrations Closed",
      "date" : "09-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/mv9kl407f9u34nl/aws.png?raw=1",
      "name" : "Amazon Web Services",
      "organiser" : "Computer Society",
      "regUrl" : "javascript:void(0)",
      "time" : "2:30 PM",
      "timeStamp" : 1549650600,
      "venue" : "Browsing Center"
    },
    "Android Development" : {
      "btnValue" : "Register",
      "date" : "14-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/x4gw437ez70mzwk/AndroidRubix.png?raw=1",
      "name" : "Android Development",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/AndroidRubix",
      "time" : "9:30 AM",
      "timeStamp" : 1552501800,
      "venue" : "MV Hall, GJB"
    },
    "AngularJS Workshop" : {
      "btnValue" : "Register",
      "date" : "12-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/z7zt9s13wori7np/363b6881-5198-4640-abc3-c3dd2762b202.png?raw=1",
      "name" : "AngularJS Workshop",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/angularRubix",
      "time" : "9:30 AM",
      "timeStamp" : 1552329000,
      "venue" : "MV Hall, GJB"
    },
    "Aspects of Language and Speech Processing" : {
      "btnValue" : "Register",
      "date" : "23-06-2020",
      "imgUrl" : "https://firebasestorage.googleapis.com/v0/b/nisbevents.appspot.com/o/events%2FAspects%20of%20language%20and%20speech%20Processing.jpeg?alt=media",
      "name" : "Aspects of Language...",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/nisbSpeechProcessing",
      "time" : "4:00 PM",
      "timeStamp" : 1592870400,
      "venue" : "Google Meet"
    },
    "Biblus" : {
      "btnValue" : "Register",
      "date" : "20-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/nvqs8n1ej1joqtp/Biblus19%20.png?raw=1",
      "name" : "Biblus",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/biblus19",
      "time" : "11:59 PM",
      "timeStamp" : 1550169100,
      "venue" : "NIE, Mysuru"
    },
    "Blind Code" : {
      "btnValue" : "Register",
      "date" : "03-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/y4x9gl4gaaiq5w8/Blind%20Coding%20%281%29.png?raw=1",
      "name" : "Blind Code",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/blindCodeNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554229800,
      "venue" : "MV Hall, GJB"
    },
    "BlockChain WS" : {
      "btnValue" : "Registrations Closed",
      "date" : "30-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/y5zzgbm50kjgu85/BlockChain%20%282%29%20%281%29.png?raw=1",
      "name" : "BlockChain WS",
      "organiser" : "NISB",
      "regUrl" : "javascript:void(0);",
      "time" : "2:30 PM",
      "timeStamp" : 1553884200,
      "venue" : "MV Hall, GJB"
    },
    "Bugsmash" : {
      "btnValue" : "Register",
      "date" : "24-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/hxc70dj7csbsiqo/bugsmash.jpeg?raw=1",
      "name" : "Bugsmash",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/Bugsmash19",
      "time" : "5:30 PM",
      "timeStamp" : 1571875200,
      "venue" : "Azeez Sait Hall"
    },
    "CS Weekly Meetup 2020" : {
      "date" : "13-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/53b213hxarmut7a/CS%20Weekly%20meetup.png?raw=1",
      "name" : "CS Weekly Meetup",
      "organiser" : "Computer Society",
      "regUrl" : "https://bit.ly/cs20weekly",
      "time" : "5:30 PM",
      "timeStamp" : 1578873600,
      "venue" : "Sir MV Auditorium"
    },
    "Challenge Accepted" : {
      "btnValue" : "Register",
      "date" : "29-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/5voeewtnboq33k2/meme-making.png?raw=1",
      "name" : "Challenge Accepted",
      "organiser" : "NISB",
      "time" : "--:--",
      "timeStamp" : 1588118400,
      "venue" : "Online"
    },
    "Code Geeks" : {
      "btnValue" : "Register",
      "date" : "10-08-2018",
      "imgUrl" : "https://www.dropbox.com/s/73k8g1s2atwhlvr/CodeGeeks.png?raw=1",
      "name" : "Code Geeks",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/CodeGeeks",
      "time" : "5:30 PM",
      "timeStamp" : 1533839400,
      "venue" : "MV Hall, GJB"
    },
    "CodeGeek2" : {
      "btnValue" : "Register",
      "date" : "11-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/w3pnv3bw0ld26xp/CodeGeeks2.0%20%284%29.png?raw=1",
      "name" : "CodeGeek 2.0",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/CodeGeeksRubix",
      "time" : "5:30 PM",
      "timeStamp" : 1552242600,
      "venue" : "MV Hall, GJB"
    },
    "CodeLabs19" : {
      "btnValue" : "Register",
      "date" : "06-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/v24ylyrnoip6j9b/CodelabsPoster.png?raw=1",
      "name" : "Codelabs",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/codelabs19",
      "time" : "5:30 PM",
      "timeStamp" : 1567728000,
      "venue" : "Programming&ASP Lab,NRN"
    },
    "CodeLabs:C  " : {
      "btnValue" : "Register",
      "date" : "01-09-2018",
      "imgUrl" : "https://www.dropbox.com/s/z953au1yl888ke3/codeLabsSmall.png?raw=1",
      "name" : "CodeLabs:C++",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/CodeNISB",
      "time" : "2:30 PM",
      "timeStamp" : 1535740200,
      "venue" : "Browsing Center"
    },
    "Codegeeks" : {
      "btnValue" : "Register",
      "date" : "23-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/73k8g1s2atwhlvr/CodeGeeks.png?raw=1",
      "name" : "Codegeeks",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/NISBcodegeeks19",
      "time" : "5:30 PM",
      "timeStamp" : 1571788800,
      "venue" : "Azeez Sait Hall"
    },
    "Codeiton" : {
      "btnValue" : "Register",
      "date" : "21-03-2020",
      "imgUrl" : "https://www.dropbox.com/s/f3p1da8qdg6lp4k/codeItOn.png?raw=1",
      "name" : "Code-it-on",
      "organiser" : "NISB",
      "time" : "04:00 PM",
      "timeStamp" : 1584748800,
      "venue" : "Online"
    },
    "Dell EMC Visit" : {
      "btnValue" : "Register",
      "date" : "17-01-2019",
      "imgUrl" : "https://www.dropbox.com/s/sr01gs6n1nh4rf4/IV%20-%202018.png?raw=1",
      "name" : "Dell EMC Visit",
      "organiser" : "NISB",
      "regUrl" : "NOLINK",
      "time" : "6:00 AM",
      "timeStamp" : 1547663400,
      "venue" : "GJB, NIE"
    },
    "Dhriti" : {
      "btnValue" : "Register",
      "date" : "02-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/9iqr62cb1yq6kqq/9362ec60-bde7-4e44-96d7-59728e883b07.png?raw=1",
      "name" : "Dhriti",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/dhritiNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1549045800,
      "venue" : "Divya Deepa"
    },
    "Dhriti20" : {
      "btnValue" : "Register",
      "date" : "18-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/gypl6o4rl2g5lm1/Dhriti.png?raw=1",
      "name" : "Dhriti",
      "organiser" : "WIE",
      "regUrl" : "https://bit.ly/wiedhriti20",
      "time" : "8:00 AM",
      "timeStamp" : 1579305600,
      "venue" : "Kanakagiri Govt School"
    },
    "Electronic Essentials" : {
      "date" : "4th & 5th September",
      "imgUrl" : "https://www.dropbox.com/s/kd1hm80d16807l7/Electronic%20Essentials.png?raw=1",
      "name" : "Electronic Essentials",
      "regUrl" : "http://bit.ly/nisbee19",
      "time" : "5:30 ",
      "venue" : "Room 115, GJB"
    },
    "Electronics Essentials" : {
      "btnValue" : "Register",
      "date" : "13-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/kd1hm80d16807l7/Electronic%20Essentials.png?raw=1",
      "name" : "Electronics Essentials",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/nisbee19",
      "time" : "2:30 PM",
      "timeStamp" : 1567555200,
      "venue" : "Room 115, GJB"
    },
    "Electronika" : {
      "btnValue" : "Register",
      "date" : "24-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/1e3pnhgzzifaynp/Electronika%20poster.png?raw=1",
      "name" : "Electronika 11.0",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/electronika11",
      "time" : "5:30 PM",
      "timeStamp" : 1569283200,
      "venue" : "Sir MV Auditorium"
    },
    "Electronika 10" : {
      "btnValue" : "Register",
      "date" : "04-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/01at59xnqpqmy43/Electronika%20%283%29%20%281%29.png?raw=1",
      "name" : "Electronika 10.0",
      "organiser" : "NISB",
      "regUrl" : "http://bit.do/electronikaNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554316200,
      "venue" : "MV Hall, GJB"
    },
    "Engineers and Healthcare" : {
      "btnValue" : "Register",
      "date" : "25-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/oulx1s1nyynehqr/adroit19inaug.jpeg?raw=1",
      "name" : "Engineers & Healthcare",
      "organiser" : "NISB",
      "time" : "10:00 AM",
      "timeStamp" : 1569369600,
      "venue" : "Sir MV Auditorium, GJB"
    },
    "Enigma" : {
      "btnValue" : "Register",
      "date" : "05-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/7e11lfzo1ncnbvv/Enigma.png?raw=1",
      "name" : "Enigma",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/enigmaNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1538677800,
      "venue" : "MV Hall, GJB"
    },
    "Everyone Has A Story" : {
      "btnValue" : "Register",
      "date" : "16-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/okyrgusdmtjbo7a/book.png?raw=1",
      "name" : "Everyone Has A Story",
      "organiser" : "NISB",
      "regUrl" : "NOLINK",
      "time" : "5:30 PM",
      "timeStamp" : 1539628200,
      "venue" : "MV Hall, GJB"
    },
    "Exploring Data Analysis" : {
      "btnValue" : "Register",
      "date" : "05-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/pmry2o0dabvq9qu/ExploringData%20Analysis%20%281%29%20%281%29.png?raw=1",
      "name" : "Exploring Data Analysis",
      "organiser" : "WIE",
      "regUrl" : "http://www.bit.ly/dataNISB",
      "time" : "10:30 AM",
      "timeStamp" : 1538677800,
      "venue" : "MV Hall"
    },
    "Fable Fiesta" : {
      "btnValue" : "Register",
      "date" : "04-05-2020",
      "imgUrl" : "https://www.dropbox.com/s/4iyklnblvg4qppq/Story%20making.png?raw=1",
      "name" : "Fable Fiesta",
      "organiser" : "NISB",
      "time" : "05:00 PM",
      "timeStamp" : 1588550400,
      "venue" : "Online"
    },
    "GBM 2020" : {
      "btnValue" : "No Registration",
      "date" : "24-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/si1e249fli760f7/GBM.png?raw=1",
      "name" : "General Body Meet",
      "organiser" : "NISB",
      "regUrl" : "#",
      "time" : "5:30 PM",
      "timeStamp" : 1548288000,
      "venue" : "Sir MV Auditorium"
    },
    "Game development" : {
      "btnValue" : "Register",
      "date" : "25-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/5xw7kxorni2eodu/Game%20Development.png?raw=1",
      "name" : "Game Dev Workshop",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/NISBgamedev",
      "time" : "10:00 AM",
      "timeStamp" : 1571961600,
      "venue" : "MV Auditorium,GJB"
    },
    "General Body Meet" : {
      "btnValue" : "Register",
      "date" : "24-01-2019",
      "imgUrl" : "https://www.dropbox.com/s/si1e249fli760f7/GBM.png?raw=1",
      "name" : "General Body Meet",
      "organiser" : "NISB",
      "regUrl" : "NOLINK",
      "time" : "5:30 PM",
      "timeStamp" : 1548268200,
      "venue" : "Azeez Sait Hall"
    },
    "Golang Workshop" : {
      "btnValue" : "Sorry, All Seats Are Filled",
      "date" : "28-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/v0e0kg7e1vomohm/goS.png?raw=1",
      "name" : "Golang Workshop",
      "organiser" : "WIE",
      "regUrl" : "javascript:void(0);",
      "time" : "9:45 AM",
      "timeStamp" : 1551292200,
      "venue" : "MV Hall, GJB"
    },
    "HFG2020" : {
      "btnValue" : "Register",
      "date" : "21-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/9jcrca4q0u4lz0w/Hardware%20focus%20group.png?raw=1",
      "name" : "Hardware Focus Group",
      "organiser" : "NISB",
      "regUrl" : "https://bit.ly/a101_hfg",
      "time" : "5:30 PM",
      "timeStamp" : 1579564800,
      "venue" : "Room No. 115, GJB"
    },
    "Hardware Focus Group" : {
      "btnValue" : "Register",
      "date" : "01-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/gml8g63ag8zypkq/hwfg.jpeg?raw=1",
      "name" : "Hardware Focus Group",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/hwfgNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1548959400,
      "venue" : "115, GJB"
    },
    "Hola Funtastic!" : {
      "btnValue" : "Register",
      "date" : "09-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/4r2bdyrvk2w2ts1/FunTastic%20%281%29.png?raw=1",
      "name" : "Hola Funtastic!",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/funNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554748200,
      "venue" : "MV Hall, GJB"
    },
    "IEEEXtreme: A Walkthrough" : {
      "btnValue" : "Register",
      "date" : "05-07-2020",
      "imgUrl" : "https://firebasestorage.googleapis.com/v0/b/nisbevents.appspot.com/o/events%2FXtreme_Walkthrough.jpeg?alt=media",
      "name" : "IEEEXtreme:Walkthrough",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/xtremeWalkthrough",
      "time" : "6:00 PM",
      "timeStamp" : 1593907200,
      "venue" : "Google Meet"
    },
    "IPL" : {
      "btnValue" : "Register",
      "date" : "27-09-2018",
      "imgUrl" : "https://www.dropbox.com/s/cmdk5ylew16k1tw/ipl.png?raw=1",
      "name" : "IPL 10.0",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/iplNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1537986600,
      "venue" : "MV Hall, GJB"
    },
    "IPL 11" : {
      "btnValue" : "Register",
      "date" : "01-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/j8kx0zpmb87bl6x/IPL%20%282%29%20%281%29.png?raw=1",
      "name" : "IPL 11.0",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/ipl11NISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554057000,
      "venue" : "MV Hall, GJB"
    },
    "IPL 12" : {
      "btnValue" : "Register",
      "date" : "23-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/0xag7m6vja5qqg5/IPL%20Poster.png?raw=1",
      "name" : "IPL 12.0",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/ipl12reg",
      "time" : "5:30 PM",
      "timeStamp" : 1569196800,
      "venue" : "Azeez Sait Hall"
    },
    "IPL13" : {
      "btnValue" : "Register",
      "date" : "20-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/bwjq0o4jf54v5w6/IPL_13.0.png?raw=1",
      "name" : "IPL 13.0",
      "organiser" : "NISB",
      "time" : "06:00 PM",
      "timeStamp" : 1587340800,
      "venue" : "Online"
    },
    "Ideathon" : {
      "btnValue" : "Register",
      "date" : "01-05-2020",
      "imgUrl" : "https://www.dropbox.com/s/g19dkh3ek56wkh1/Ideathon.png?raw=1",
      "name" : "Ideathon",
      "organiser" : "NISB",
      "time" : "10:30 AM",
      "timeStamp" : 1588291200,
      "venue" : "Online"
    },
    "Industrial Visit" : {
      "btnValue" : "Register",
      "date" : "28-02-2020",
      "imgUrl" : "https://www.dropbox.com/s/2seo3f6mchedn4s/Industrial%20visit.png?raw=1",
      "name" : "Dell EMC IV",
      "organiser" : "NISB",
      "regUrl" : "https://bit.ly/nisbdelliv",
      "time" : "--:--",
      "timeStamp" : 1582848000,
      "venue" : "Dell EMC, Bangalore"
    },
    "Inspiro" : {
      "date" : "03-03-2018",
      "imgUrl" : "https://scontent.fblr1-3.fna.fbcdn.net/v/t1.0-0/p526x296/28059364_362677647534333_6130086664855413189_n.jpg?_nc_cat=0&oh=19f68d8ae5afc25048ece81c989217f9&oe=5C02FCD5",
      "name" : "Inspiro",
      "organiser" : "WIE",
      "time" : "10:00 AM",
      "timeStamp" : 1520015400,
      "venue" : "MV Hall, GJB"
    },
    "Inspiro'19" : {
      "btnValue" : "Register",
      "date" : "27-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/yuc2z8sovaujquh/inaug.png?raw=1",
      "name" : "Inspiro'19",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/cbInspiro",
      "time" : "10:00 AM",
      "timeStamp" : 1551205800,
      "venue" : "MV Hall, GJB"
    },
    "Interview Ace" : {
      "btnValue" : "Register",
      "date" : "23-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/o8qovfgvr8j29lh/webinar.png?raw=1",
      "name" : "How to ace an interview",
      "organiser" : "NISB",
      "time" : "06:00 PM",
      "timeStamp" : 1587600000,
      "venue" : "Online"
    },
    "Intro to Python" : {
      "btnValue" : "Register",
      "date" : "02-11-2018",
      "imgUrl" : "https://www.dropbox.com/s/2y11ar6hjbxouj0/wiePython.png?raw=1",
      "name" : "Intro to Python",
      "organiser" : "WIE",
      "regUrl" : "NOLINK",
      "time" : "5:30 PM",
      "timeStamp" : 1541097000,
      "venue" : "MV Hall, GJB"
    },
    "Journey Through the Core" : {
      "btnValue" : "Register",
      "date" : "16-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/obqvbprgt9vnysv/Journey%20Through%20the%20Core.png?raw=1",
      "name" : "JTTC",
      "organiser" : "NISB",
      "regUrl" : "blahblah",
      "time" : "5:30 PM",
      "timeStamp" : 1579132800,
      "venue" : "Sir MV Auditorium"
    },
    "Just-Hack" : {
      "btnValue" : "Register",
      "date" : "31-01-2019",
      "imgUrl" : "https://www.dropbox.com/s/ab8166ehbjkccay/Hackathon_HE.png?raw=1",
      "name" : "Just-Hack",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/justHack",
      "time" : "9:00 AM",
      "timeStamp" : 1548873000,
      "venue" : "MV Hall, GJB"
    },
    "Linux Inst Drive" : {
      "btnValue" : "Free and Open for all",
      "date" : "13-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/j6t5ti106840fsk/LinuxInstalltion%20%282%29.png?raw=1",
      "name" : "Linux Inst. Drive",
      "organiser" : "Computer Society",
      "regUrl" : "javascript:void(0);",
      "time" : "5:30 PM",
      "timeStamp" : 1552415400,
      "venue" : "MV Hall, GJB"
    },
    "MATLAB Workshop" : {
      "btnValue" : "Sorry, All Seats Are Filled",
      "date" : "01-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/skyc11jvzehlzii/matlab.jpeg?raw=1",
      "name" : "MATLAB Workshop",
      "organiser" : "WIE",
      "regUrl" : "javascript:void(0);",
      "time" : "9:45 AM",
      "timeStamp" : 1551378600,
      "venue" : "MV Hall, GJB"
    },
    "ML Techtalk" : {
      "btnValue" : "Register",
      "date" : "27-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/yzlmrvmayjpneer/ML%20techtalk.jpeg?raw=1",
      "name" : "ML Tech Talk",
      "organiser" : "NISB",
      "time" : "10:00 AM",
      "timeStamp" : 1569542400,
      "venue" : "Sir MV Auditorium, GJB"
    },
    "ML Workshop" : {
      "btnValue" : "Register",
      "date" : "24-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/ixf9zucfc4k1gs6/ML%20Workshop%20Rubix.png?raw=1",
      "name" : "ML Workshop",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/MLWS2019",
      "time" : "10:00 AM",
      "timeStamp" : 1571875200,
      "venue" : "Sir MV Auditorium"
    },
    "Micropython" : {
      "btnValue" : "Register",
      "date" : "20-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/sep1n2acr69q68t/micropython.jpeg?raw=1",
      "name" : "Micropython Workshop",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/wiemipy",
      "time" : "10:00 AM",
      "timeStamp" : 1571529600,
      "venue" : "Room 411, NRN"
    },
    "Mock Placements" : {
      "btnValue" : "Register",
      "date" : "05-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/szpf0iwcjpku6xr/MockPlacements%20%281%29%20%281%29.png?raw=1",
      "name" : "Mock Placements",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/mpNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554402600,
      "venue" : "MV Hall, GJB"
    },
    "Mockplacements20" : {
      "btnValue" : "Register",
      "date" : "22-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/ejaplb1zslbvuej/Mock_Placement.png?raw=1",
      "name" : "Mock Placements",
      "organiser" : "NISB",
      "time" : "06:00 PM",
      "timeStamp" : 1587513600,
      "venue" : "Online"
    },
    "Multicore Architecture" : {
      "btnValue" : "Register",
      "date" : "27-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/o5nxq3l0r5kng5o/Shruti%20maam%20workshop.png?raw=1",
      "name" : "Multicore Architecture",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/nisbamca",
      "time" : "2:00 PM",
      "timeStamp" : 1569542400,
      "venue" : "Programming&ASP Lab,NRN"
    },
    "NIE Summer of Code" : {
      "date" : "02-06-2018",
      "imgUrl" : "https://scontent.fblr1-4.fna.fbcdn.net/v/t1.0-0/s480x480/31102424_1724119027664542_7553791467777277998_n.jpg?_nc_cat=0&oh=6e03c6f41d24ddcc663336cf63337d3c&oe=5C1338AA",
      "name" : "NIE Summer of Code",
      "organiser" : "NISB",
      "time" : "10:00 AM",
      "timeStamp" : 1527877800,
      "venue" : "SR Hall, Admin Block"
    },
    "NISBXtreme" : {
      "btnValue" : "Register",
      "date" : "24-08-2020",
      "imgUrl" : "https://firebasestorage.googleapis.com/v0/b/nisbevents.appspot.com/o/events%2FNISBXtreme.png?alt=media",
      "name" : "NISBXtreme",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/nisbxtreme",
      "time" : "10:00 AM",
      "timeStamp" : 1598227200,
      "venue" : "Hackerrank"
    },
    "Panel Discussion" : {
      "btnValue" : "Register",
      "date" : "02-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/58gq7ksk9pztspp/panel.png?raw=1",
      "name" : "Panel Discussion",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/pdInspiro",
      "time" : "11:30 AM",
      "timeStamp" : 1551465000,
      "venue" : "MV Hall, GJB"
    },
    "Quizlamatic" : {
      "btnValue" : "Register",
      "date" : "26-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/t85gcbdojn2ows7/tech1%20quiz.png?raw=1",
      "name" : "Quizlamatic",
      "organiser" : "NISB",
      "time" : "06:00 PM",
      "timeStamp" : 1587859200,
      "venue" : "Online"
    },
    "Quizwiz" : {
      "btnValue" : "Register",
      "date" : "20-03-2020",
      "imgUrl" : "https://www.dropbox.com/s/6c5odoxq6k88d61/quizwiz.jpeg?raw=1",
      "name" : "Quizwiz 2.0",
      "organiser" : "NISB",
      "time" : "07:30 PM",
      "timeStamp" : 1584662400,
      "venue" : "Online"
    },
    "Raspberry Pi WS" : {
      "btnValue" : "Register",
      "date" : "10-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/bb4m4hojb8vhhol/R%20Pi%20%281%29.png?raw=1",
      "name" : "Raspberry Pi WS",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/rpiAnkura19",
      "time" : "9:30 AM",
      "timeStamp" : 1554834600,
      "venue" : "MV Hall, GJB"
    },
    "Reverse Coding" : {
      "btnValue" : "Register",
      "date" : "03-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/f4chzjbb7u07t7h/reverse.png?raw=1",
      "name" : "Reverse Coding",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/revNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1538505000,
      "venue" : "MV Hall, GJB"
    },
    "Riddler" : {
      "btnValue" : "Register",
      "date" : "10-08-2020",
      "imgUrl" : "https://firebasestorage.googleapis.com/v0/b/nisbevents.appspot.com/o/events%2FRiddler.png?alt=media",
      "name" : "Riddler",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/riddler20",
      "time" : "4:00 PM",
      "timeStamp" : 1597017600,
      "venue" : "Hackerrank"
    },
    "Robocode" : {
      "btnValue" : "Register",
      "date" : "08-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/h8r35egddjyz8xi/RoboCode%20%281%29.png?raw=1",
      "name" : "Robocode",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/robocodeNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1554661800,
      "venue" : "Browsing Center"
    },
    "Rubix" : {
      "btnValue" : "Bring Out The Geek in You",
      "date" : "11-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/uw6024hy6p7n2gf/Rubix%20%284%29.png?raw=1",
      "name" : "Rubix",
      "organiser" : "Computer Society",
      "regUrl" : "javascript:void(0);",
      "time" : "10:00 AM",
      "timeStamp" : 1552242600,
      "venue" : "MV Hall, GJB"
    },
    "Rubix inaug" : {
      "btnValue" : "Register",
      "date" : "23-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/k0g71n4l4a2v8tw/AI%20rubix%20inaug.png?raw=1",
      "name" : "AI Techtalk",
      "organiser" : "Computer Society",
      "time" : "10:00 AM",
      "timeStamp" : 1571788800,
      "venue" : "Sir MV Auditorium, GJB"
    },
    "RubixMainTeaser" : {
      "btnValue" : "Register",
      "date" : "23-10-2019",
      "imgUrl" : "https://www.dropbox.com/s/h5ko45uis1iaqge/Rubix%20main%20poster.png?raw=1",
      "name" : "Rubix 2.0",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/rubix",
      "time" : "10:00 AM",
      "timeStamp" : 1571788799,
      "venue" : "Sir MV Auditorium, GJB"
    },
    "SFG 2020" : {
      "btnValue" : "Register",
      "date" : "23-01-2020",
      "imgUrl" : "https://www.dropbox.com/s/u8fko6n71lueigx/Copy%20of%20Software%20focus%20group.png?raw=1",
      "name" : "Software Focus Group",
      "organiser" : "NISB",
      "regUrl" : "https://bit.ly/nisbsfg20",
      "time" : "5:30 PM",
      "timeStamp" : 1548201600,
      "venue" : "Sir MV Auditorium"
    },
    "Sahaay" : {
      "btnValue" : "Contribute",
      "date" : "20-08-2018",
      "imgUrl" : "https://www.dropbox.com/s/whbxl652shradfe/RS.png?raw=1",
      "name" : "Sahaay",
      "organiser" : "NISB",
      "regUrl" : "https://www.dropbox.com/s/pipkq0ga8v3mbhg/Rescue.png?raw=1",
      "time" : "nil",
      "timeStamp" : 1534789800,
      "venue" : "Desk"
    },
    "SelfHosted Developer" : {
      "btnValue" : "Register",
      "date" : "09-04-2019",
      "imgUrl" : "https://www.dropbox.com/s/n6xz8vtqiivlzbz/SelfHosted%20%281%29.png?raw=1",
      "name" : "SelfHosted Developer",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/devOpsNISB",
      "time" : "10:00 AM",
      "timeStamp" : 1554748200,
      "venue" : "MV Hall, GJB"
    },
    "Simplicode" : {
      "btnValue" : "Register",
      "date" : "28-08-2019",
      "imgUrl" : "https://www.dropbox.com/s/3l1t8d76qvzl9de/SimpliCode.png?raw=1",
      "name" : "Simplicode",
      "organiser" : "Computer Society",
      "regUrl" : "http://bit.ly/nisbcssimplicode",
      "time" : "5:30 PM",
      "timeStamp" : 1566950400,
      "venue" : "Browsing Centre"
    },
    "Software Focus Group" : {
      "btnValue" : "Register",
      "date" : "09-11-2018",
      "imgUrl" : "https://www.dropbox.com/s/paqbfsua7e1pefm/swfg.png?raw=1",
      "name" : "Software Focus Group",
      "organiser" : "NISB",
      "regUrl" : "NOLINK",
      "time" : "5:30 PM",
      "timeStamp" : 1541701800,
      "venue" : "MV Hall, GJB"
    },
    "Sparks" : {
      "btnValue" : "Register",
      "date" : "27-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/t3dtjlncm71wacm/sparks.jpeg?raw=1",
      "name" : "Sparks",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/sparksinspiro",
      "time" : "5:30 PM",
      "timeStamp" : 1551205800,
      "venue" : "MV Hall, GJB"
    },
    "Talk on Open Source" : {
      "btnValue" : "Free and Open for all",
      "date" : "11-03-2019",
      "imgUrl" : "https://www.dropbox.com/s/l8kwlthk2wgab6u/IMG-20190309-WA0010.jpeg?raw=1",
      "name" : "Talk on Open Source",
      "organiser" : "Computer Society",
      "regUrl" : "javascript:void(0);",
      "time" : "10:00 AM",
      "timeStamp" : 1552242600,
      "venue" : "MV Hall, GJB"
    },
    "Talk on Photonics" : {
      "btnValue" : "Open For All",
      "date" : "06-10-2018",
      "imgUrl" : "https://www.dropbox.com/s/qksgu72pu5cqjom/photonics.png?raw=1",
      "name" : "Talk on Photonics",
      "organiser" : "NISB",
      "regUrl" : "",
      "time" : "10:00 AM",
      "timeStamp" : 1538764200,
      "venue" : "MV Hall, GJB"
    },
    "Technical Paper Writing" : {
      "btnValue" : "Registrations Closed",
      "date" : "06-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/j81vfzafrsi520s/paper.jpeg?raw=1",
      "name" : "Technical Paper Writing",
      "organiser" : "NISB",
      "regUrl" : "javascript:void(0)",
      "time" : "5:30 PM",
      "timeStamp" : 1549391400,
      "venue" : "MV Hall, GJB"
    },
    "Techwiz" : {
      "btnValue" : "Event Over",
      "date" : "25-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/1ukozhg8r6xsrzz/techwiz.jpeg?raw=1",
      "name" : "Techwiz",
      "organiser" : "WIE",
      "regUrl" : "javascript:void(0);",
      "time" : "5:30 PM",
      "timeStamp" : 1551033000,
      "venue" : "MV Hall, GJB"
    },
    "The Road Ahead" : {
      "btnValue" : "Register",
      "date" : "26-08-2020",
      "imgUrl" : "https://firebasestorage.googleapis.com/v0/b/nisbevents.appspot.com/o/events%2FThe_Road_Ahead.png?alt=media",
      "name" : "The Road Ahead",
      "organiser" : "NISB",
      "regUrl" : "",
      "time" : "5:00 PM",
      "timeStamp" : 1598400000,
      "venue" : "Google Meet"
    },
    "Transistor: The Silicon Stone" : {
      "btnValue" : "Register",
      "date" : "25-08-2018",
      "imgUrl" : "https://www.dropbox.com/s/uwrznjr1knydl09/ttss%20%281%29.png?raw=1",
      "name" : "Transistor: The Silicon St",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/transistorNISB",
      "time" : "2:30 PM",
      "timeStamp" : 1535135400,
      "venue" : "Room 115, GJB"
    },
    "Triviyeah" : {
      "btnValue" : "Register",
      "date" : "20-09-2019",
      "imgUrl" : "https://www.dropbox.com/s/sswffdc8q187hho/triviyeah.jpeg?raw=1",
      "name" : "Triviyeahh!!",
      "organiser" : "NISB",
      "regUrl" : "http:bit.ly/nisbtriviyeah",
      "time" : "5:30 PM",
      "timeStamp" : 1568937600,
      "venue" : "Azeez Sait Hall"
    },
    "Vision API" : {
      "btnValue" : "Register",
      "date" : "10-08-2019",
      "imgUrl" : "https://www.dropbox.com/s/bjffh5x8pnt0ods/VisionPosterFinal.png?raw=1",
      "name" : "Vision API Workshop",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/nisbvisionapi",
      "time" : "10:00 AM",
      "timeStamp" : 1565395200,
      "venue" : "Sir MV Auditorium, GJB"
    },
    "Walky Talky" : {
      "btnValue" : "Register",
      "date" : "07-09-2018",
      "imgUrl" : "https://www.dropbox.com/s/ywze53l378y27k7/walkyTalkSmall.png?raw=1",
      "name" : "Walky Talky",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/walkNISB",
      "time" : "5:30 PM",
      "timeStamp" : 1536258600,
      "venue" : "MV Hall"
    },
    "Webfury" : {
      "btnValue" : "Register",
      "date" : "23-03-2020",
      "imgUrl" : "https://www.dropbox.com/s/44c43o8sgmrqevt/Web%20dev%20poster.png?raw=1",
      "name" : "Web Fury",
      "organiser" : "NISB",
      "time" : "08:00 PM",
      "timeStamp" : 1584921600,
      "venue" : "Online"
    },
    "Weekly Meetup - Git" : {
      "btnValue" : "Only CS Members",
      "date" : "05-02-2019",
      "imgUrl" : "https://www.dropbox.com/s/pv10r9yhwyzv8b4/cw.png?raw=1",
      "name" : "Weekly Meetup - Git",
      "organiser" : "Computer Society",
      "regUrl" : "",
      "time" : "5:30 PM",
      "timeStamp" : 1549305000,
      "venue" : "MV Hall, GJB"
    },
    "codewino" : {
      "btnValue" : "Register",
      "date" : "28-03-2020",
      "imgUrl" : "https://www.dropbox.com/s/pxrhe2n40f26hl3/Hardware%20Hackathon.png?raw=1",
      "name" : "Code-win-o",
      "organiser" : "NISB",
      "time" : "08:00 PM",
      "timeStamp" : 1585353600,
      "venue" : "Online"
    },
    "electronika12" : {
      "btnValue" : "Register",
      "date" : "28-04-2020",
      "imgUrl" : "https://www.dropbox.com/s/gl3wgzxkmf0tl5n/Electronika%2012.0.png?raw=1",
      "name" : "Electronika 12.0",
      "organiser" : "NISB",
      "time" : "06:00 PM",
      "timeStamp" : 1588032000,
      "venue" : "Online"
    },
    "ex-QuizMe" : {
      "btnValue" : "Register",
      "date" : "28-09-2018",
      "imgUrl" : "https://www.dropbox.com/s/rbrddx825vlo7gx/XQuizMe_Updated.png?raw=1",
      "name" : "ex-QuizMe",
      "organiser" : "NISB",
      "regUrl" : "http://bit.ly/xquizme",
      "time" : "5:30 PM",
      "timeStamp" : 1538073000,
      "venue" : "MV Hall, GJB"
    },
    "hackthevirus" : {
      "btnValue" : "Register",
      "date" : "27-03-2020",
      "imgUrl" : "https://www.dropbox.com/s/d7wuw52t6ywjcyv/HACK_THE_VIRUS.png?raw=1",
      "name" : "Hack The Virus",
      "organiser" : "NISB",
      "time" : "12:00 PM",
      "timeStamp" : 1585267200,
      "venue" : "Online"
    },
    "Ω - Series - Ω" : {
      "btnValue" : "Register",
      "date" : "20-08-2018",
      "imgUrl" : "https://www.dropbox.com/s/0cnhngz4or26bt3/OSO.png?raw=1",
      "name" : "Ω - Series - Ω",
      "organiser" : "WIE",
      "regUrl" : "http://bit.ly/OhmSeriesOhm",
      "time" : "5:30 PM",
      "timeStamp" : 1534703400,
      "venue" : "MV Hall, GJB"
    }
  }
}
